In [0]:
import cv2
import numpy as np
from scipy.cluster.vq import vq, kmeans, whiten #Euclidean distance K-means

from sklearn.cluster import AgglomerativeClustering

In [0]:
k = np.random.rand(100).reshape(10,10)

In [0]:
codebook, distortion = kmeans(k, int(np.sqrt(k.size)))

In [0]:
codebook

array([[ 0.70763747,  0.47472526,  0.59266943,  0.41427778,  0.73966094,
         0.71429352,  0.3116987 ,  0.37437582,  0.49511535,  0.54568372],
       [ 0.33988453,  0.27481267,  0.35582304,  0.49555138,  0.20876142,
         0.4180715 ,  0.73762992,  0.60294112,  0.77119873,  0.5981769 ]])

In [0]:
#TO-DO Use Kmeans if K is well know. The clusters should result in low variance
#Check agglomerative clustering when K is not know. It works well for more samples + clusters
#Check Minibatch Kmeans to process features in batches. Scales very well.

model = AgglomerativeClustering()
y = model.fit(k)

In [0]:
y


AgglomerativeClustering(affinity='euclidean', compute_full_tree='auto',
            connectivity=None, linkage='ward', memory=None, n_clusters=2,
            pooling_func=<function mean at 0x7faa8810af28>)

In [0]:
y.labels_

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [0]:
model = AgglomerativeClustering(5)
y = model.fit(k)
y.labels_

array([3, 0, 1, 4, 0, 2, 2, 0, 1, 2])